### ISSUE TITLE
rmrk1 minor typo

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-docs#6]
[rmrk1.md](https://docs.rmrk.app/rmrk1)
is: "Kusama is a blockchain without smart contracts. We cannot write logic onto it, so we cannot do things NFTs"
suggested fix: "Kusama is a blockchain without smart contracts. We cannot write logic onto it, so we cannot do things like NFTs"

**Comment by Swader** [comment]
No longer relevant
